version: '3.3'

services:

  php:
    image: ${REGISTRY:-}cscart_base/webhook:php-${PHP70_VERSION:-7.0.30}-fpm-alpine3.7
    restart: always
    environment:
      LOGSPOUT: ignore
    networks:
      app:
        aliases:
          - php-fpm