version: '3.3'

services:

  php:
    image: ${REGISTRY:-}cscart_base/webhook:php-${PHP70_VERSION:-7.0.30}-fpm-alpine3.7
    restart: always
    environment:
      LOGSPOUT: ignore
      WEBHOOK_CI_PROXY_CI_URL: ${WEBHOOK_CI_PROXY_CI_URL}
      WEBHOOK_CI_PROXY_ACCESS_TOKEN: ${WEBHOOK_CI_PROXY_ACCESS_TOKEN}
    networks:
      app:
        aliases:
          - php-fpm
