version: '3.3'

services:

  nginx:
    image: ${REGISTRY}cscart_base/cscart:nginx-${NGINX_VERSION}-alpine3.7
    command: /bin/sh -c "envsubst '$${WEBHOOK_ADDRESS}' < /etc/nginx/templates/webhook.dist > /etc/nginx/conf.d/webhook.conf && nginx-debug -g 'daemon off;'"
    restart: always
    networks:
      app:
        aliases:
          - teamcity-webhook
          - ${WEBHOOK_ADDRESS}

  php:
    image: ${REGISTRY}cscart_base/cscart:php-${PHP70_VERSION}-fpm-alpine3.7
    restart: always
    networks:
      app:
        aliases:
          - php-fpm