version: '3'
services:

############################################################################

  webhook_php:
    build:
      args:
        REGISTRY: ${REGISTRY}
        PHP_VERSION: ${PHP70_VERSION}
        PROJECT: webhook
      context: ../images/base_images
      dockerfile: php70-fpm.dockerfile
    image: ${REGISTRY}cscart_base/webhook:php-${PHP70_VERSION}-fpm-alpine3.7

  webhook_nginx:
    build:
      args:
        REGISTRY: ${REGISTRY}
        NGINX_VERSION: ${NGINX_VERSION}
        PROJECT: webhook
      context: ../images/base_images
      dockerfile: nginx.dockerfile
    image: ${REGISTRY}cscart_base/webhook:nginx-${NGINX_VERSION}-alpine3.7

############################################################################

  teamcity_agent:
    build:
      context: ../images/base_images/teamcity/agent
    image: ${REGISTRY}cscart_base/teamcity:agent-jetbrains

  teamcity_postgres:
    build:
      context: ../images/base_images/teamcity/postgres
    image: ${REGISTRY}cscart_base/teamcity:postgres-9.6

  teamcity_proxy:
    build:
      args:
        REGISTRY: ${REGISTRY}
        NGINX_VERSION: ${NGINX_VERSION}
        PROJECT: proxy
      context: ../images/base_images/
      dockerfile: nginx.dockerfile
    image: ${REGISTRY}cscart_base/teamcity:proxy-nginx-${NGINX_VERSION}-alpine3.7