version: '3'
services:

  teamcity_agent:
    build:
      context: ../images/base_images/teamcity/agent
    image: ${REGISTRY}cscart_base/teamcity:agent-jetbrains

  teamcity_postgres:
    build:
      context: ../images/base_images/teamcity/postgres
    image: ${REGISTRY}cscart_base/teamcity:postgres-9.6

  teamcity_proxy:
    build:
      args:
        REGISTRY: ${REGISTRY}
      context: ../images/base_images/proxy/nginx
    image: ${REGISTRY}cscart_base/teamcity:proxy-nginx-stable-alpine3.7

  webhook_php:
    build:
      context: ../images/base_images/webhook
      args:
        REGISTRY: ${REGISTRY}
        PHP_VERSION: ${PHP70_VERSION}
        TZ: UTC
        PROJECT: webhook
    image: ${REGISTRY}cscart_base/webhook:php-${PHP70_VERSION}-fpm-alpine3.7